Pandas is a fast, powerful, and open-source Python library used for data manipulation and analysis. It provides highly flexible data structures that allow you to work easily with structured, tabular data—much like a digital spreadsheet or an SQL database table. The name originates from the econometrics term "Panel Data".

Pandas relies primarily on two data structures to handle data:
Series: A one-dimensional labeled array that can hold any data type (e.g., a single column of numbers or strings).
DataFrame: A two-dimensional, table-like data structure with labeled rows and columns (the most frequently used Pandas object).

In [1]:
import pandas as pd

In [5]:
## Series
## A Pandas Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). 
## It is similar to a column in a spreadsheet or a SQL table. Each element in a Series has an associated label, known as an index.

import pandas as pd
data = [1, 2, 3, 4, 5]
series =pd.Series(data)
print ("Series: \n", series)
print(type(series))

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [7]:
## Create a series from dictionary
data={'a': 1, 'b': 2, 'c': 3}
series = pd.Series(data)
print(series)

a    1
b    2
c    3
dtype: int64

In [10]:
data=[10, 20, 30]
index=['a', 'b', 'c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [ ]:
## DataFrame
## Create a DataFrame from a dictionary of lists
data = {
    'Name': ['Aryan', 'Bob', 'Charlie'],
    'Age': [21, 30, 35],
    'City': ['Pune', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
<class 'pandas.DataFrame'>

In [5]:
## Create a Data Frame from a list of dictionaries
import pandas as pd

data = [
    {'Name': 'Aryan', 'Age': 21, 'City': 'Pune'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Los Angeles'},
    {'Name': 'Charlie', 'Age': 35, 'City': 'Chicago'},
    {'Name': 'David', 'Age': 28, 'City': 'New York'}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age         City
0    Aryan   21         Pune
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   28     New York
<class 'pandas.DataFrame'>

In [ ]:
# import pandas as pd
# df = pd.read_csv('data.csv')
# print(df.head(5)) #THis is for the top 5 data
#print(df.tail(5))  THIS IS FOR THE LAST 5 data

  Series_reference   Period  Data_value Suppressed STATUS    UNITS  Magnitude  \
0    BDCQ.SF1AA2CA  2016.06    1116.386        NaN      F  Dollars          6
1    BDCQ.SF1AA2CA  2016.09    1070.874        NaN      F  Dollars          6
2    BDCQ.SF1AA2CA  2016.12    1054.408        NaN      F  Dollars          6
3    BDCQ.SF1AA2CA  2017.03    1010.665        NaN      F  Dollars          6
4    BDCQ.SF1AA2CA  2017.06    1233.700        NaN      F  Dollars          6

                          Subject  \
0  Business Data Collection - BDC
1  Business Data Collection - BDC
2  Business Data Collection - BDC
3  Business Data Collection - BDC
4  Business Data Collection - BDC

                                             Group            Series_title_1  \
0  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)
1  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)
2  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)
3  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)
4  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)

         Series_title_2  Series_title_3 Series_title_4  Series_title_5
0  Forestry and Logging  Current prices     Unadjusted             NaN
1  Forestry and Logging  Current prices     Unadjusted             NaN
2  Forestry and Logging  Current prices     Unadjusted             NaN
3  Forestry and Logging  Current prices     Unadjusted             NaN
4  Forestry and Logging  Current prices     Unadjusted             NaN

In [7]:
# Accessing Data in DataFrame
import pandas as pd

df

      Name  Age         City
0    Aryan   21         Pune
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   28     New York

In [8]:
df.loc[0]  # Access the first row of the DataFrame

Name    Aryan
Age        21
City     Pune
Name: 0, dtype: object

In [9]:
df.iloc[0]

Name    Aryan
Age        21
City     Pune
Name: 0, dtype: object

In [10]:
## Accessing a specific column
df['Name']  # Access the 'Name' column

0      Aryan
1        Bob
2    Charlie
3      David
Name: Name, dtype: str

In [11]:
## accessing a specific row and column
df.at[df.index[0], 'Name']  # Access the 'Name' of the first row

'Aryan'

In [12]:
df.iat[2, 2]

'Chicago'

In [14]:
## Data Manipulation with Dataframe 
df

      Name  Age         City
0    Aryan   21         Pune
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   28     New York

In [ ]:
df.drop('City', axis=1) # the default axis is 0, which means it will drop rows. To drop a column, we need to specify axis=1.

      Name  Age
0    Aryan   21
1      Bob   30
2  Charlie   35
3    David   28

In [16]:
df

      Name  Age         City
0    Aryan   21         Pune
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   28     New York